In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [3]:
regions = pd.read_csv(
    "../../../data/raw/airports/regions.csv"
)

In [4]:
regions.head()

,id,code,local_code,name,continent,iso_country,wikipedia_link,keywords
0,302811,AD-02,02,Canillo Parish,EU,AD,https://en.wikipedia.org/wiki/Canillo,Airports in Canillo Parish
1,302812,AD-03,03,Encamp Parish,EU,AD,https://en.wikipedia.org/wiki/Encamp,Airports in Encamp Parish
2,302813,AD-04,04,La Massana Parish,EU,AD,https://en.wikipedia.org/wiki/La_Massana,Airports in La Massana Parish
3,302814,AD-05,05,Ordino Parish,EU,AD,https://en.wikipedia.org/wiki/Ordino,Airports in Ordino Parish
4,302815,AD-06,06,Sant Julià de Lòria Parish,EU,AD,https://en.wikipedia.org/wiki/Sant_Julià_de_Lòria,Airports in Sant Julià de Lòria Parish

In [5]:
regions.tail()

,id,code,local_code,name,continent,iso_country,wikipedia_link,keywords
3977,306317,ZW-MS,MS,Matabeleland South Province,AF,ZW,https://en.wikipedia.org/wiki/Matabeleland_Sou...,Airports in Matabeleland South Province
3978,306318,ZW-MV,MV,Masvingo Province,AF,ZW,https://en.wikipedia.org/wiki/Masvingo_Province,Airports in Masvingo Province
3979,306319,ZW-MW,MW,Mashonaland West Province,AF,ZW,https://en.wikipedia.org/wiki/Mashonaland_West...,Airports in Mashonaland West Province
3980,306320,ZW-U-A,U-A,(unassigned),AF,ZW,NaN,Airports in (unassigned)
3981,306321,ZZ-U-A,U-A,(unassigned),AF,ZZ,NaN,Airports in (unassigned)

In [6]:
print("Rows :", regions.shape[0])
print("Columns :", regions.shape[1])

Rows : 3982
Columns : 8

In [7]:
regions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3982 entries, 0 to 3981
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              3982 non-null   int64
 1   code            3982 non-null   object
 2   local_code      3978 non-null   object
 3   name            3982 non-null   object
 4   continent       3542 non-null   object
 5   iso_country     3967 non-null   object
 6   wikipedia_link  3713 non-null   object
 7   keywords        3853 non-null   object
dtypes: int64(1), object(7)
memory usage: 249.0+ KB

In [8]:
regions.columns

Index(['id', 'code', 'local_code', 'name', 'continent', 'iso_country',
       'wikipedia_link', 'keywords'],
      dtype='object')

In [9]:
missing = pd.DataFrame({
    "Missing Values": regions.isnull().sum(),
    "Percentage": (
        regions.isnull().mean()*100
    ).round(2)
})

missing.sort_values(
    by="Percentage",
    ascending=False
)

                Missing Values  Percentage
continent                  440       11.05
wikipedia_link             269        6.76
keywords                   129        3.24
iso_country                 15        0.38
local_code                   4        0.10
name                         0        0.00
id                           0        0.00
code                         0        0.00

In [10]:
print(
    "Duplicate Rows:",
    regions.duplicated().sum()
)

Duplicate Rows: 0

In [11]:
regions["code"].duplicated().sum()

np.int64(0)

In [12]:
regions.head()

regions.info()

regions.columns

regions.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3982 entries, 0 to 3981
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              3982 non-null   int64
 1   code            3982 non-null   object
 2   local_code      3978 non-null   object
 3   name            3982 non-null   object
 4   continent       3542 non-null   object
 5   iso_country     3967 non-null   object
 6   wikipedia_link  3713 non-null   object
 7   keywords        3853 non-null   object
dtypes: int64(1), object(7)
memory usage: 249.0+ KB

(3982, 8)