In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
regions = pd.read_csv("../../../data/raw/airports/regions.csv")

In [3]:
regions_clean = regions.copy()

In [4]:
missing = pd.DataFrame({
    "Missing Values": regions_clean.isnull().sum(),
    "Percentage": (
        regions_clean.isnull().mean() * 100
    ).round(2)
})

missing.sort_values(
    by="Percentage",
    ascending=False
)

                Missing Values  Percentage
continent                  440       11.05
wikipedia_link             269        6.76
keywords                   129        3.24
iso_country                 15        0.38
local_code                   4        0.10
name                         0        0.00
id                           0        0.00
code                         0        0.00

In [5]:
columns_to_drop = [
    "wikipedia_link",
    "keywords"
]

regions_clean.drop(
    columns=columns_to_drop,
    inplace=True
)

In [6]:
text_columns = regions_clean.select_dtypes(
    include="object"
).columns

for col in text_columns:
    regions_clean[col] = (
        regions_clean[col]
        .str.strip()
    )

In [7]:
regions_clean["code"] = (
    regions_clean["code"]
    .str.upper()
)

regions_clean["local_code"] = (
    regions_clean["local_code"]
    .str.upper()
)

regions_clean["continent"] = (
    regions_clean["continent"]
    .str.upper()
)

regions_clean["iso_country"] = (
    regions_clean["iso_country"]
    .str.upper()
)

In [8]:
missing_after = pd.DataFrame({
    "Missing Values": regions_clean.isnull().sum(),
    "Percentage": (
        regions_clean.isnull().mean() * 100
    ).round(2)
})

missing_after

             Missing Values  Percentage
id                        0        0.00
code                      0        0.00
local_code                4        0.10
name                      0        0.00
continent               440       11.05
iso_country              15        0.38

In [10]:
print(
    "Duplicate Rows:",
    regions_clean.duplicated().sum()
)

Duplicate Rows: 0

In [11]:
print(
    "Duplicate Region Codes:",
    regions_clean["code"].duplicated().sum()
)

Duplicate Region Codes: 0

In [12]:
regions_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3982 entries, 0 to 3981
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           3982 non-null   int64
 1   code         3982 non-null   object
 2   local_code   3978 non-null   object
 3   name         3982 non-null   object
 4   continent    3542 non-null   object
 5   iso_country  3967 non-null   object
dtypes: int64(1), object(5)
memory usage: 186.8+ KB

In [13]:
regions_clean.to_csv(
    "../../../data/processed/airports/regions/regions_processed.csv",
    index=False
)

print("Regions dataset cleaned and saved successfully.")

Regions dataset cleaned and saved successfully.

## Data Cleaning Summary

The regions dataset was cleaned by removing non-essential reference columns (`wikipedia_link` and `keywords`) while retaining all attributes required for geographic enrichment and future dataset integration. Text fields were standardized by trimming whitespace and converting region, country, and continent codes to uppercase. Missing values in `local_code`, `continent`, and `iso_country` were intentionally preserved because this dataset serves as a reference table, and modifying missing values could reduce data integrity. Final validation confirmed that the cleaned dataset contains no duplicate records or duplicate region codes and is suitable for exploratory analysis and later integration with the airport dataset.