In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [3]:
countries = pd.read_csv(
    "../../../data/raw/airports/countries.csv"
)

In [4]:
countries.head()

,id,code,name,continent,wikipedia_link,keywords
0,302672,AD,Andorra,EU,https://en.wikipedia.org/wiki/Andorra,Andorran airports
1,302618,AE,United Arab Emirates,AS,https://en.wikipedia.org/wiki/United_Arab_Emir...,"UAE,مطارات في الإمارات العربية المتحدة"
2,302619,AF,Afghanistan,AS,https://en.wikipedia.org/wiki/Afghanistan,NaN
3,302722,AG,Antigua and Barbuda,NaN,https://en.wikipedia.org/wiki/Antigua_and_Barbuda,Antiguan airports
4,302723,AI,Anguilla,NaN,https://en.wikipedia.org/wiki/Anguilla,NaN

In [5]:
countries.tail()

,id,code,name,continent,wikipedia_link,keywords
244,302609,YT,Mayotte,AF,https://en.wikipedia.org/wiki/Mayotte,Airports in Mayotte
245,302610,ZA,South Africa,AF,https://en.wikipedia.org/wiki/South_Africa,South African airports
246,302611,ZM,Zambia,AF,https://en.wikipedia.org/wiki/Zambia,Zambian airports
247,302612,ZW,Zimbabwe,AF,https://en.wikipedia.org/wiki/Zimbabwe,Zimbabwan airports
248,302613,ZZ,Unknown or unassigned country,AF,https://en.wikipedia.org/wiki/Unknown_or_unass...,Airports in Unknown or unassigned country

In [6]:
countries.sample(5)

,id,code,name,continent,wikipedia_link,keywords
38,302562,CF,Central African Republic,AF,https://en.wikipedia.org/wiki/Central_African_...,Airports in Central African Republic
126,302699,LI,Liechtenstein,EU,https://en.wikipedia.org/wiki/Liechtenstein,Airports in Liechtenstein
169,302655,OM,Oman,AS,https://en.wikipedia.org/wiki/Oman,مطارات عمان
204,302614,SS,South Sudan,AF,https://en.wikipedia.org/wiki/South_Sudan,South Sudanese airports
51,302628,CX,Christmas Island,AS,https://en.wikipedia.org/wiki/Christmas_Island,Airports in Christmas Island

In [7]:
print("Rows :", countries.shape[0])
print("Columns :", countries.shape[1])

Rows : 249
Columns : 6

In [8]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              249 non-null    int64
 1   code            248 non-null    object
 2   name            249 non-null    object
 3   continent       208 non-null    object
 4   wikipedia_link  249 non-null    object
 5   keywords        233 non-null    object
dtypes: int64(1), object(5)
memory usage: 11.8+ KB

In [9]:
missing = pd.DataFrame({
    "Missing Values": countries.isnull().sum(),
    "Percentage": (
        countries.isnull().mean()*100
    ).round(2)
})

missing

                Missing Values  Percentage
id                           0        0.00
code                         1        0.40
name                         0        0.00
continent                   41       16.47
wikipedia_link               0        0.00
keywords                    16        6.43

In [10]:
print(
    countries.duplicated().sum()
)

0

In [11]:
countries["code"].duplicated().sum()

np.int64(0)

In [12]:
countries.head()

countries.info()

countries.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              249 non-null    int64
 1   code            248 non-null    object
 2   name            249 non-null    object
 3   continent       208 non-null    object
 4   wikipedia_link  249 non-null    object
 5   keywords        233 non-null    object
dtypes: int64(1), object(5)
memory usage: 11.8+ KB

Index(['id', 'code', 'name', 'continent', 'wikipedia_link', 'keywords'], dtype='object')