In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [3]:
runways = pd.read_csv("../../../data/raw/airports/runways.csv")

In [4]:
runways_clean = runways.copy()

In [5]:
missing = pd.DataFrame({
    "Missing Values": runways_clean.isnull().sum(),
    "Percentage": (
        runways_clean.isnull().mean() * 100
    ).round(2)
})

missing.sort_values(
    by="Percentage",
    ascending=False
)

                           Missing Values  Percentage
he_displaced_threshold_ft           45248       94.12
le_displaced_threshold_ft           45007       93.62
he_elevation_ft                     35000       72.80
le_elevation_ft                     34774       72.33
le_heading_degT                     32999       68.64
he_longitude_deg                    32531       67.67
he_latitude_deg                     32533       67.67
le_longitude_deg                    32424       67.45
le_latitude_deg                     32411       67.42
he_heading_degT                     31219       64.94
he_ident                             7601       15.81
width_ft                             3013        6.27
surface                               503        1.05
length_ft                             289        0.60
le_ident                              243        0.51
id                                      0        0.00
airport_ident                           0        0.00
airport_ref                             0        0.00
lighted                                 0        0.00
closed                                  0        0.00

In [6]:
runways_clean["length_ft"] = runways_clean["length_ft"].fillna(
    runways_clean["length_ft"].median()
)

In [7]:
runways_clean["width_ft"] = runways_clean["width_ft"].fillna(
    runways_clean["width_ft"].median()
)

In [8]:
runways_clean["surface"] = (
    runways_clean["surface"]
    .fillna("UNKNOWN")
)

In [9]:
runways_clean["le_ident"] = (
    runways_clean["le_ident"]
    .fillna("UNKNOWN")
)

runways_clean["he_ident"] = (
    runways_clean["he_ident"]
    .fillna("UNKNOWN")
)

In [10]:
text_columns = runways_clean.select_dtypes(
    include="object"
).columns

for col in text_columns:
    runways_clean[col] = (
        runways_clean[col]
        .str.strip()
        .str.upper()
    )

In [11]:
missing_after = pd.DataFrame({
    "Missing Values": runways_clean.isnull().sum(),
    "Percentage": (
        runways_clean.isnull().mean() * 100
    ).round(2)
})

missing_after.sort_values(
    by="Percentage",
    ascending=False
)

                           Missing Values  Percentage
he_displaced_threshold_ft           45248       94.12
le_displaced_threshold_ft           45007       93.62
he_elevation_ft                     35000       72.80
le_elevation_ft                     34774       72.33
le_heading_degT                     32999       68.64
he_longitude_deg                    32531       67.67
he_latitude_deg                     32533       67.67
le_longitude_deg                    32424       67.45
le_latitude_deg                     32411       67.42
he_heading_degT                     31219       64.94
airport_ref                             0        0.00
id                                      0        0.00
length_ft                               0        0.00
airport_ident                           0        0.00
le_ident                                0        0.00
closed                                  0        0.00
width_ft                                0        0.00
surface                                 0        0.00
lighted                                 0        0.00
he_ident                                0        0.00

In [12]:
print(
    "Duplicate Rows:",
    runways_clean.duplicated().sum()
)

Duplicate Rows: 0

In [13]:
print(
    "Duplicate Runway IDs:",
    runways_clean["id"].duplicated().sum()
)

Duplicate Runway IDs: 0

In [14]:
runways_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48074 entries, 0 to 48073
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         48074 non-null  int64
 1   airport_ref                48074 non-null  int64
 2   airport_ident              48074 non-null  object
 3   length_ft                  48074 non-null  float64
 4   width_ft                   48074 non-null  float64
 5   surface                    48074 non-null  object
 6   lighted                    48074 non-null  int64
 7   closed                     48074 non-null  int64
 8   le_ident                   48074 non-null  object
 9   le_latitude_deg            15663 non-null  float64
 10  le_longitude_deg           15650 non-null  float64
 11  le_elevation_ft            13300 non-null  float64
 12  le_heading_degT            15075 non-null  float64
 13  le_displaced_threshold_ft  3067 non-null   float64
 14  he_ident                   48074 non-null  object
 15  he_latitude_deg            15541 non-null  float64
 16  he_longitude_deg           15543 non-null  float64
 17  he_elevation_ft            13074 non-null  float64
 18  he_heading_degT            16855 non-null  float64
 19  he_displaced_threshold_ft  2826 non-null   float64
dtypes: float64(12), int64(4), object(4)
memory usage: 7.3+ MB

In [16]:
runways_clean.to_csv(
    "../../../data/processed/airports/runways/runways_processed.csv",
    index=False
)

print("Runways dataset cleaned and saved successfully.")

Runways dataset cleaned and saved successfully.

## Data Cleaning Summary

The runway dataset was cleaned by addressing missing values in key operational attributes while preserving detailed runway-end information for future analysis. Missing runway lengths and widths were imputed using the median values, while missing surface types and runway identifiers were replaced with the value `UNKNOWN`. Text fields were standardized by removing leading and trailing whitespace and converting categorical values to uppercase. Highly incomplete runway-end attributes were intentionally retained because they may provide additional operational information during later stages of feature engineering or future extensions of the project. Final validation confirmed that the cleaned dataset contains no duplicate records or duplicate runway identifiers and is suitable for exploratory data analysis.